### ISSUE TITLE
Lock / contention when not using a transaction and exceeding pool limit

### ISSUE THREAD

**Issue by saurori** [gobuffalo/buffalo-pop#28]
I've discovered (the hard way) that if you use the transaction middleware `app.Use(popmw.Transaction(models.DB))`, but you DO NOT use the transaction in a request handler (i.e. just use `models.DB` directly), the entire application will lock up if the number of concurrent requests exceeds your `pool` setting for the DB connection.

To test this, create a new buffalo app. Configure the database and add some sample data. Sample config:
```yaml
development:
  dialect: postgres
  database: my_app
  user: {{envOr "DATABASE_USER" "postgres"}}
  host: {{envOr "DATABASE_HOST" "127.0.0.1"}}
  pool: {{envOr "DATABASE_CONNS" "3"}}
```

In a handler, query the db and DO NOT use the `tx` stored in context, example:
```go
func HomeHandler(c buffalo.Context) error {
	var em []models.ExampleModel

	if err := models.DB.All(&em); err != nil {
		return err
	}

	return c.Render(http.StatusOK, r.HTML("index.html"))
}
```

Make concurrent requests to the endpoint exceeding the `pool`, I did 10 concurrent requests. The application will completely lock up and not respond at all. Removing the transaction middleware eliminates the problem.
